// lib/repositories/pest_repository.dart
import '../models/pest.dart';
import '../models/category.dart';

class PestRepository {
  // Singleton pattern
  static final PestRepository _instance = PestRepository._internal();
  
  factory PestRepository() => _instance;
  
  PestRepository._internal();

  // Mock data for categories
  final List<Category> _categories = [
    Category(
      id: '1',
      name: 'Insects',
      description: 'Six-legged arthropods that may infest homes and crops',
      iconPath: 'assets/insects.gif',
    ),
    Category(
      id: '2',
      name: 'Rodents',
      description: 'Small mammals characterized by a single pair of continuously growing incisors',
      iconPath: 'assets/rodents.gif',
    ),
    Category(
      id: '3',
      name: 'Fungi',
      description: 'Organisms that can cause mold and plant diseases',
      iconPath: 'assets/fungi.gif',
    ),
    Category(
      id: '4',
      name: 'Birds',
      description: 'Avian species that can cause property damage and spread diseases',
      iconPath: 'assets/birds.gif',
    ),
    Category(
      id: '5',
      name: 'Mites',
      description: 'Tiny arachnids that infest plants, animals, and indoor environments',
      iconPath: 'assets/mites.gif',
    ),
    Category(
      id: '6',
      name: 'Mollusks',
      description: 'Snails and slugs that damage plants and thrive in moist environments',
      iconPath: 'assets/mollusks.gif',
    ),
    Category(
      id: '7',
      name: 'Nematodes',
      description: 'Microscopic worms that attack plant roots and agricultural crops',
      iconPath: 'assets/nematodes.gif',
    ),
    Category(
      id: '8',
      name: 'Weeds',
      description: 'Unwanted plant species that compete with crops and garden plants',
      iconPath: 'assets/weeds.gif',
    ),
    Category(
      id: '9',
      name: 'Microbial',
      description: 'Bacteria and viruses that cause diseases in plants, animals, and humans',
      iconPath: 'assets/microbial_pests.gif',
    ),
    Category(
      id: '10',
      name: 'Arachnids',
      description: 'Eight-legged creatures like spiders and scorpions that can infest homes',
      iconPath: 'assets/arachnids.gif',
    ),
  ];

  // Mock data for pests
  final List<Pest> _pests = [
    Pest(
      id: '1',
      name: 'House Fly',
      scientificName: 'Musca domestica',
      category: '1',
      description: 'Common fly found around homes that can spread disease.',
      prevention: 'Keep food covered, dispose of garbage regularly, use screens on windows.',
      treatment: 'Fly swatters, sticky traps, insecticidal sprays, or natural predators like Venus flytraps.',
      imagePath: 'assets/house_fly.jpg',
    ),
    Pest(
      id: '1',
      name: 'Termite',  
      scientificName: 'Isoptera',
      category: '1', 
      description: 'Termites are small, pale insects that feed on wood and cellulose materials, causing extensive structural damage. They live in colonies with a caste system, including workers, soldiers, and reproductive termites.',  
      prevention: 'Reduce moisture around structures, seal cracks in foundations, and use termite-resistant materials. Regular inspections can help detect infestations early.', 
      treatment: 'Apply liquid termiticides around the foundation, use termite bait stations, or hire professional fumigation services for severe infestations.',
      imagePath: 'assets/termite.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Cockroach',  
      scientificName: 'Blattodea',
      category: '1', 
      description: 'Cockroaches are nocturnal insects with flattened, oval bodies and long antennae. They thrive in warm, humid environments and are known for spreading diseases through food contamination.',  
      prevention: 'Keep food sealed, clean up crumbs and spills, fix leaks, and seal entry points around the house.', 
      treatment: 'Use cockroach baits, insecticide sprays, boric acid, or diatomaceous earth. Professional pest control may be necessary for large infestations.',
      imagePath: 'assets/cockroach.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Mosquito',  
      scientificName: 'Culicidae',
      category: '1', 
      description: 'Mosquitoes are small, flying insects with long, slender legs and a proboscis for feeding on blood. They are vectors of diseases like malaria, dengue, and Zika virus.',  
      prevention: 'Eliminate standing water, use mosquito nets and repellents, and install window screens to prevent entry.', 
      treatment: 'Apply insecticides to breeding sites, use mosquito fogging, and introduce biological control agents like mosquito fish (Gambusia).',
      imagePath: 'assets/mosquito.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Bed Bug',  
      scientificName: 'Cimex lectularius',
      category: '1', 
      description: 'Bed bugs are small, reddish-brown insects that feed on human blood. They hide in cracks, crevices, and bedding, emerging at night to feed.',  
      prevention: 'Regularly inspect and clean bedding, avoid bringing used furniture indoors, and seal cracks in walls.', 
      treatment: 'Wash bedding in hot water, use insecticide sprays, steam treatment, and professional heat treatments for severe infestations.',
      imagePath: 'assets/bed_bug.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Ant',  
      scientificName: 'Formicidae',
      category: '1', 
      description: 'Ants are social insects that live in large colonies. They vary in size and color and can become household pests by foraging for food indoors.',  
      prevention: 'Store food in sealed containers, clean up spills, and seal entry points to prevent access.', 
      treatment: 'Use bait traps, boric acid, and insecticide sprays. Destroying the colony by targeting the queen is essential for long-term control.',
      imagePath: 'assets/ant.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Flea',  
      scientificName: 'Siphonaptera',
      category: '1', 
      description: 'Fleas are tiny, wingless parasites that feed on the blood of animals and humans. They cause itching, allergic reactions, and can transmit diseases.',  
      prevention: 'Regularly groom and treat pets with flea preventatives, vacuum carpets and upholstery frequently, and wash pet bedding.', 
      treatment: 'Use flea shampoos, sprays, and oral medications for pets. Treat the environment with insect growth regulators (IGRs) and vacuum thoroughly.',
      imagePath: 'assets/flea.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Aphid',  
      scientificName: 'Aphidoidea',
      category: '1', 
      description: 'Aphids are small, soft-bodied insects that feed on plant sap, causing leaf curling, yellowing, and reduced plant growth. They reproduce rapidly and can transmit plant viruses.',  
      prevention: 'Encourage natural predators like ladybugs, use reflective mulch, and avoid excessive nitrogen fertilizers.', 
      treatment: 'Spray plants with insecticidal soap, neem oil, or introduce beneficial insects like lacewings to control infestations.',
      imagePath: 'assets/aphid.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Japanese Beetle',  
      scientificName: 'Popillia japonica',
      category: '1', 
      description: 'Japanese beetles are metallic green and copper-colored insects that feed on the foliage of ornamental plants, skeletonizing leaves and damaging crops.',  
      prevention: 'Use row covers to protect plants, remove beetles manually, and avoid planting highly susceptible plants.', 
      treatment: 'Apply neem oil, introduce parasitic nematodes or milky spore bacteria to control larvae, and use traps cautiously.',
      imagePath: 'assets/japanese_beetle.jpg',
    ),
    Pest( 
      id: '1',
      name: 'Stink Bug',  
      scientificName: 'Pentatomidae',
      category: '1', 
      description: 'Stink bugs are shield-shaped insects that release a foul odor when disturbed. They feed on fruits, vegetables, and ornamental plants, causing blemishes and reduced yields.',  
      prevention: 'Seal cracks around windows and doors, remove vegetation near structures, and use row covers in gardens.', 
      treatment: 'Hand-pick bugs, use insecticidal soap, or apply pyrethroid-based insecticides for severe infestations.',
      imagePath: 'assets/stink_bug.jpg',
    ),
    Pest(
      id: '2',
      name: 'House Mouse',
      scientificName: 'Mus musculus',
      category: '2',
      description: 'Small rodent commonly found in homes, capable of spreading disease and causing damage.',
      prevention: 'Seal entry points, keep food stored in containers, maintain cleanliness.',
      treatment: 'Traps, rodenticides (with caution), or professional pest control services.',
      imagePath: 'assets/house_mouse.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Norway Rat',
      scientificName: 'Rattus norvegicus',
      category: '2',
      description: 'Large brown rat with a blunt nose and a thick body, known for burrowing and contaminating food sources.',
      prevention: 'Eliminate food sources, seal entry points, and remove clutter.',
      treatment: 'Use baited traps, rodenticides, or hire professional exterminators.',
      imagePath: 'assets/norway_rat.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Roof Rat',
      scientificName: 'Rattus rattus',
      category: '2',
      description: 'Slim, black or brown rat with a pointed nose, known for climbing and nesting in attics and trees.',
      prevention: 'Trim tree branches near roofs, store food securely, and seal small entry holes.',
      treatment: 'Snap traps, bait stations, and rodenticides as necessary.',
      imagePath: 'assets/roof_rat.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Deer Mouse',
      scientificName: 'Peromyscus maniculatus',
      category: '2',
      description: 'Small rodent with white underbelly, known to carry hantavirus and often found in rural areas.',
      prevention: 'Seal gaps in structures, clean up food sources, and avoid storing firewood near homes.',
      treatment: 'Snap traps, live traps, and proper sanitation to prevent infestations.',
      imagePath: 'assets/deer_mouse.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Cotton Rat',
      scientificName: 'Sigmodon hispidus',
      category: '2',
      description: 'Medium-sized rodent with coarse fur, commonly found in fields and grassy areas.',
      prevention: 'Maintain clear yards, remove tall vegetation, and secure food sources.',
      treatment: 'Use bait stations, traps, and remove harborage areas.',
      imagePath: 'assets/cotton_rat.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Kangaroo Rat',
      scientificName: 'Dipodomys spp.',
      category: '2',
      description: 'Small rodent with large hind legs for jumping, primarily found in deserts and arid regions.',
      prevention: 'Keep storage areas sealed and reduce food attractants.',
      treatment: 'Live traps, exclusion methods, and maintaining a clean environment.',
      imagePath: 'assets/kangaroo_rat.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Woodrat (Pack Rat)',
      scientificName: 'Neotoma spp.',
      category: '2',
      description: 'Rodent known for collecting shiny objects and nesting in burrows or structures.',
      prevention: 'Seal cracks, remove debris, and avoid leaving attractants outside.',
      treatment: 'Live trapping and relocating, using snap traps, or professional control services.',
      imagePath: 'assets/woodrat.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Vole',
      scientificName: 'Microtus spp.',
      category: '2',
      description: 'Small, stocky rodent that tunnels through lawns and damages plant roots.',
      prevention: 'Keep grass trimmed, install barriers, and reduce ground cover.',
      treatment: 'Use vole traps, rodenticide baits, or introduce natural predators like owls.',
      imagePath: 'assets/vole.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Pocket Gopher',
      scientificName: 'Geomys spp.',
      category: '2',
      description: 'Burrowing rodent that damages gardens and agricultural lands by creating extensive tunnels.',
      prevention: 'Install underground barriers, reduce food sources, and maintain dry soil conditions.',
      treatment: 'Use gopher traps, fumigation methods, or bait applications.',
      imagePath: 'assets/pocket_gopher.jpg',
    ),
    Pest( 
      id: '2',
      name: 'Chipmunk',
      scientificName: 'Tamias spp.',
      category: '2',
      description: 'Small striped rodent that digs burrows and can damage gardens by feeding on plants.',
      prevention: 'Remove food sources, use fencing around gardens, and block burrow entrances.',
      treatment: 'Live trapping, repellents, and exclusion methods.',
      imagePath: 'assets/chipmunk.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Black Mold',
      scientificName: 'Stachybotrys chartarum',
      category: '3',
      description: 'A toxic mold that thrives in damp environments and can cause respiratory issues.',
      prevention: 'Control indoor humidity, fix leaks, and ensure proper ventilation.',
      treatment: 'Use mold-killing solutions like bleach, remove contaminated materials, and improve airflow.',
      imagePath: 'assets/black_mold.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Powdery Mildew',
      scientificName: 'Erysiphales spp.',
      category: '3',
      description: 'A fungal disease that appears as white, powdery spots on plant leaves and stems.',
      prevention: 'Provide good air circulation, avoid overhead watering, and use resistant plant varieties.',
      treatment: 'Apply fungicides, prune infected areas, and remove plant debris.',
      imagePath: 'assets/powdery_mildew.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Downy Mildew',
      scientificName: 'Peronosporaceae spp.',
      category: '3',
      description: 'A plant disease that appears as yellow or brown leaf spots with a fuzzy underside growth.',
      prevention: 'Ensure proper plant spacing, avoid excessive moisture, and use resistant plant strains.',
      treatment: 'Apply copper-based fungicides and remove infected plant parts.',
      imagePath: 'assets/downy_mildew.jpg',
    ),
    Pest( 
      id: '3',
      name: 'White Mold',
      scientificName: 'Sclerotinia sclerotiorum',
      category: '3',
      description: 'A fungal disease that causes wilting, white cotton-like growth, and rotting in plants.',
      prevention: 'Avoid overcrowding plants, improve drainage, and rotate crops.',
      treatment: 'Apply fungicides, remove infected plants, and sanitize garden tools.',
      imagePath: 'assets/white_mold.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Leaf Rust',
      scientificName: 'Puccinia spp.',
      category: '3',
      description: 'A fungal disease that causes orange or reddish-brown spots on plant leaves.',
      prevention: 'Choose rust-resistant plant varieties, maintain proper spacing, and reduce leaf wetness.',
      treatment: 'Use fungicidal sprays and prune infected leaves.',
      imagePath: 'assets/leaf_rust.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Corn Smut',
      scientificName: 'Ustilago maydis',
      category: '3',
      description: 'A fungus that forms large, swollen galls on corn kernels and stalks.',
      prevention: 'Plant resistant corn varieties and remove infected plants immediately.',
      treatment: 'Remove and destroy affected plants; no chemical control is available.',
      imagePath: 'assets/corn_smut.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Gray Mold',
      scientificName: 'Botrytis cinerea',
      category: '3',
      description: 'A fungal disease that causes fuzzy grayish mold on fruits, flowers, and vegetables.',
      prevention: 'Ensure proper airflow, remove plant debris, and keep plants dry.',
      treatment: 'Use fungicides and remove infected plant parts.',
      imagePath: 'assets/gray_mold.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Root Rot',
      scientificName: 'Phytophthora spp.',
      category: '3',
      description: 'A fungal infection that causes roots to decay, leading to wilting and plant death.',
      prevention: 'Ensure well-draining soil, avoid overwatering, and use disease-free plants.',
      treatment: 'Apply fungicides and remove affected roots.',
      imagePath: 'assets/root_rot.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Clubroot',
      scientificName: 'Plasmodiophora brassicae',
      category: '3',
      description: 'A fungal disease affecting cruciferous vegetables, causing swollen, distorted roots.',
      prevention: 'Practice crop rotation, maintain soil pH above 7.2, and improve drainage.',
      treatment: 'Use soil amendments like lime and remove infected plants.',
      imagePath: 'assets/clubroot.jpg',
    ),
    Pest( 
      id: '3',
      name: 'Anthracnose',
      scientificName: 'Colletotrichum spp.',
      category: '3',
      description: 'A fungal disease that creates dark, sunken spots on leaves, stems, and fruits.',
      prevention: 'Avoid excessive watering, prune affected areas, and use resistant plant varieties.',
      treatment: 'Apply copper-based fungicides and remove infected parts.',
      imagePath: 'assets/anthracnose.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Pigeon',
      scientificName: 'Columba livia',
      category: '4',
      description: 'A common urban bird known for roosting on buildings and creating droppings that can damage structures and spread disease.',
      prevention: 'Install bird spikes, seal entry points, and avoid feeding pigeons.',
      treatment: 'Use bird deterrents such as netting, ultrasonic repellents, and professional bird control services.',
      imagePath: 'assets/pigeon.jpg',
    ),
    Pest(  
      id: '4',
      name: 'House Sparrow',
      scientificName: 'Passer domesticus',
      category: '4',
      description: 'A small, invasive bird species that nests in buildings and competes with native birds.',
      prevention: 'Use bird netting, seal gaps in structures, and remove food sources.',
      treatment: 'Install exclusion devices, use humane traps, and remove nesting materials.',
      imagePath: 'assets/house_sparrow.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Starling',
      scientificName: 'Sturnus vulgaris',
      category: '4',
      description: 'A highly social bird that forms large flocks, often causing noise, crop damage, and sanitation issues.',
      prevention: 'Use noise deterrents, remove food sources, and seal entry points in buildings.',
      treatment: 'Install bird spikes, use netting, and deploy bird-scaring devices.',
      imagePath: 'assets/starling.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Crow',
      scientificName: 'Corvus brachyrhynchos',
      category: '4',
      description: 'An intelligent bird known for scavenging garbage and crops, sometimes causing damage to farmlands.',
      prevention: 'Use scarecrows, reflective objects, and limit food availability.',
      treatment: 'Deploy noise deterrents, install bird netting, and use bird control lasers.',
      imagePath: 'assets/crow.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Seagull',
      scientificName: 'Larus spp.',
      category: '4',
      description: 'A coastal bird that scavenges food from human activities, often becoming aggressive.',
      prevention: 'Use covered trash bins, install bird spikes, and avoid feeding them.',
      treatment: 'Deploy bird deterrent systems like wires and netting, and use bird-repelling gels.',
      imagePath: 'assets/seagull.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Canada Goose',
      scientificName: 'Branta canadensis',
      category: '4',
      description: 'A large bird known for aggressive behavior and excessive droppings in parks and water sources.',
      prevention: 'Use fencing around water bodies, apply repellents to grass areas, and limit food availability.',
      treatment: 'Use trained dogs, noise deterrents, and habitat modification techniques.',
      imagePath: 'assets/canada_goose.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Woodpecker',
      scientificName: 'Picidae spp.',
      category: '4',
      description: 'A bird that pecks on trees and wooden structures, causing damage to buildings.',
      prevention: 'Use visual deterrents, cover affected areas with netting, and install sound deterrents.',
      treatment: 'Apply bird-repelling gels and use reflective tapes to discourage pecking.',
      imagePath: 'assets/woodpecker.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Grackle',
      scientificName: 'Quiscalus quiscula',
      category: '4',
      description: 'A loud, invasive bird species that forms large flocks and damages crops.',
      prevention: 'Use noise deterrents, remove food sources, and install bird spikes.',
      treatment: 'Deploy avian control lasers, use bird netting, and remove nesting areas.',
      imagePath: 'assets/grackle.jpg',
    ),
    Pest(  
      id: '4',
      name: 'Myna',
      scientificName: 'Acridotheres tristis',
      category: '4',
      description: 'An invasive bird species that competes with native birds and causes noise pollution.',
      prevention: 'Seal nesting sites, use bird spikes, and remove food sources.',
      treatment: 'Install trapping devices and use sound deterrents to reduce populations.',
      imagePath: 'assets/myna.jpg',
    ),
    Pest(  
      id: '4',
      name: 'European Robin',
      scientificName: 'Erithacus rubecula',
      category: '4',
      description: 'A small songbird that can become a pest when nesting in structures and causing droppings.',
      prevention: 'Use bird netting, seal small openings, and limit food sources.',
      treatment: 'Use humane relocation techniques and install bird-repellent systems.',
      imagePath: 'assets/european_robin.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Spider Mite',
      scientificName: 'Tetranychus urticae',
      category: '5',
      description: 'A tiny arachnid that feeds on plant sap, causing yellowing, webbing, and leaf drop.',
      prevention: 'Maintain humidity, avoid plant overcrowding, and regularly inspect leaves for early signs.',
      treatment: 'Use insecticidal soap, neem oil, or introduce predatory mites like Phytoseiulus persimilis.',
      imagePath: 'assets/spider_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Dust Mite',
      scientificName: 'Dermatophagoides spp.',
      category: '5',
      description: 'Microscopic mites that thrive in household dust and can trigger allergies and asthma.',
      prevention: 'Use allergen-proof bedding, vacuum frequently with HEPA filters, and maintain low humidity.',
      treatment: 'Wash bedding in hot water, use anti-dust mite sprays, and apply acaricides if necessary.',
      imagePath: 'assets/dust_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Scabies Mite',
      scientificName: 'Sarcoptes scabiei',
      category: '5',
      description: 'A parasitic mite that burrows into human skin, causing severe itching and rash.',
      prevention: 'Avoid close contact with infected individuals and wash clothing and bedding frequently.',
      treatment: 'Apply prescribed scabicidal creams like permethrin and treat all household members.',
      imagePath: 'assets/scabies_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Chigger Mite',
      scientificName: 'Trombiculidae spp.',
      category: '5',
      description: 'Tiny red mites that bite humans and animals, causing itchy welts and irritation.',
      prevention: 'Wear protective clothing, use insect repellent, and avoid tall grass and wooded areas.',
      treatment: 'Apply antihistamines, hydrocortisone cream, and take warm baths to relieve itching.',
      imagePath: 'assets/chigger_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Clover Mite',
      scientificName: 'Bryobia praetiosa',
      category: '5',
      description: 'Small red mites that invade homes in large numbers, leaving red stains when crushed.',
      prevention: 'Seal cracks, keep vegetation trimmed away from buildings, and use perimeter treatments.',
      treatment: 'Vacuum mites, apply insecticidal soap, or use residual insecticides around entry points.',
      imagePath: 'assets/clover_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Varroa Mite',
      scientificName: 'Varroa destructor',
      category: '5',
      description: 'A parasite that attacks honeybees, weakening colonies and transmitting viruses.',
      prevention: 'Maintain strong colonies, monitor hives regularly, and use resistant bee strains.',
      treatment: 'Apply oxalic acid, thymol-based treatments, or introduce biotechnical control methods.',
      imagePath: 'assets/varroa_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Bird Mite',
      scientificName: 'Dermanyssus gallinae',
      category: '5',
      description: 'A mite that infests birds and can bite humans, causing irritation and itching.',
      prevention: 'Regularly clean bird coops, remove abandoned nests, and seal entry points in buildings.',
      treatment: 'Use insecticidal sprays, apply diatomaceous earth, and treat affected birds with acaricides.',
      imagePath: 'assets/bird_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Rat Mite',
      scientificName: 'Ornithonyssus bacoti',
      category: '5',
      description: 'A blood-feeding mite that infests rodents and may bite humans when rodent hosts die.',
      prevention: 'Eliminate rodent infestations, seal entry points, and maintain a clean environment.',
      treatment: 'Use residual insecticides, treat rodent nesting areas, and apply anti-itch creams for bites.',
      imagePath: 'assets/rat_mite.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Rust Mite',
      scientificName: 'Phyllocoptruta oleivora',
      category: '5',
      description: 'A tiny mite that damages citrus trees by causing fruit discoloration and leaf damage.',
      prevention: 'Monitor orchards, maintain tree health, and encourage natural predators.',
      treatment: 'Apply sulfur-based miticides, horticultural oils, or release predatory mites.',
      imagePath: 'assets/rust_mite.jpg',
    ),
        Pest(  
      id: '5',
      name: 'Itch Mite',
      scientificName: 'Pyemotes spp.',
      category: '5',
      description: 'A microscopic mite that causes intense itching and skin irritation after biting humans.',
      prevention: 'Avoid handling infested grain, straw, or stored products, and use protective clothing.',
      treatment: 'Apply corticosteroid creams, antihistamines, and take warm showers to relieve symptoms.',
      imagePath: 'assets/itch_mite.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Garden Snail',
      scientificName: 'Cornu aspersum',
      category: '6',
      description: 'A common land snail that feeds on plants, causing damage to leaves, stems, and fruits.',
      prevention: 'Use barriers like copper tape, remove hiding spots, and encourage natural predators like birds.',
      treatment: 'Apply iron phosphate-based baits, hand-pick snails at night, and use diatomaceous earth.',
      imagePath: 'assets/garden_snail.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Slug',
      scientificName: 'Arion spp.',
      category: '6',
      description: 'Soft-bodied mollusks that eat plant material, leaving large irregular holes in leaves.',
      prevention: 'Maintain dry soil, use mulch, and remove debris that provides shelter.',
      treatment: 'Apply slug pellets, use beer traps, or introduce predatory beetles and nematodes.',
      imagePath: 'assets/slug.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Golden Apple Snail',
      scientificName: 'Pomacea canaliculata',
      category: '6',
      description: 'A freshwater snail that damages rice paddies by consuming young plants.',
      prevention: 'Use physical barriers, maintain water levels properly, and introduce natural predators like ducks.',
      treatment: 'Apply molluscicides, hand-remove snails, and use traps.',
      imagePath: 'assets/golden_apple_snail.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Giant African Snail',
      scientificName: 'Lissachatina fulica',
      category: '6',
      description: 'A large land snail that consumes a wide range of crops and can spread diseases.',
      prevention: 'Quarantine imported plants, remove eggs and adults manually, and avoid excessive moisture.',
      treatment: 'Use salt, apply iron phosphate baits, and introduce natural enemies like predatory snails.',
      imagePath: 'assets/giant_african_snail.jpg',
    ),
    Pest(  
      id: '6',
      name: 'New Zealand Mud Snail',
      scientificName: 'Potamopyrgus antipodarum',
      category: '6',
      description: 'An invasive aquatic snail that competes with native species and disrupts ecosystems.',
      prevention: 'Clean and dry boats, fishing gear, and footwear before moving to new water bodies.',
      treatment: 'Use controlled chemical treatments in infested waters and introduce biological control agents.',
      imagePath: 'assets/new_zealand_mud_snail.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Channeled Apple Snail',
      scientificName: 'Pomacea maculata',
      category: '6',
      description: 'A large freshwater snail that feeds on aquatic plants, harming wetlands and crops.',
      prevention: 'Monitor waterways, manually remove egg masses, and introduce biological control methods.',
      treatment: 'Apply molluscicides, drain infested areas, and hand-pick snails.',
      imagePath: 'assets/channeled_apple_snail.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Rosy Wolfsnail',
      scientificName: 'Euglandina rosea',
      category: '6',
      description: 'A predatory snail that feeds on other snails, including beneficial and endangered species.',
      prevention: 'Prevent introduction to new areas and avoid releasing into non-native environments.',
      treatment: 'Manual removal and habitat management to reduce its impact on native species.',
      imagePath: 'assets/rosy_wolfsnail.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Marisa Cornuarietis',
      scientificName: 'Marisa cornuarietis',
      category: '6',
      description: 'A large aquatic snail that can outcompete native snails and damage aquatic vegetation.',
      prevention: 'Prevent accidental release into the wild and monitor for population growth.',
      treatment: 'Use physical removal, introduce natural predators, and apply targeted molluscicides.',
      imagePath: 'assets/marisa_cornuarietis.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Zebra Mussel',
      scientificName: 'Dreissena polymorpha',
      category: '6',
      description: 'An invasive freshwater mollusk that clogs pipes, disrupts ecosystems, and damages boats.',
      prevention: 'Clean, drain, and dry all boats and equipment before moving to new water bodies.',
      treatment: 'Use specialized filters, apply molluscicide treatments, and introduce biological control agents.',
      imagePath: 'assets/zebra_mussel.jpg',
    ),
    Pest(  
      id: '6',
      name: 'Asian Clam',
      scientificName: 'Corbicula fluminea',
      category: '6',
      description: 'An invasive freshwater bivalve that disrupts water flow and competes with native species.',
      prevention: 'Inspect and clean boats, nets, and gear to prevent the spread.',
      treatment: 'Apply targeted molluscicides, use manual removal, and encourage natural predation.',
      imagePath: 'assets/asian_clam.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Root-Knot Nematode',
      scientificName: 'Meloidogyne spp.',
      category: '7',
      description: 'Microscopic roundworms that attack plant roots, causing galls or knots, leading to stunted growth and reduced yields.',
      prevention: 'Rotate crops, use resistant plant varieties, and practice soil solarization.',
      treatment: 'Apply nematicides, introduce beneficial nematodes, and improve soil health with organic amendments.',
      imagePath: 'assets/rootknot_nematode.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Cyst Nematode',
      scientificName: 'Heterodera spp.',
      category: '7',
      description: 'Parasitic nematodes that form cysts in plant roots, reducing nutrient uptake and causing yellowing and wilting.',
      prevention: 'Use resistant crop varieties, rotate crops, and remove infected plants.',
      treatment: 'Apply biological control agents like Pasteuria bacteria and use nematicides selectively.',
      imagePath: 'assets/cyst_nematode.JPG',
    ),
    Pest(  
      id: '7',
      name: 'Lance Nematode',
      scientificName: 'Hoplolaimus spp.',
      category: '7',
      description: 'Nematodes that burrow into plant roots, causing necrosis, stunted growth, and wilting.',
      prevention: 'Improve soil drainage, use cover crops, and maintain proper fertilization.',
      treatment: 'Apply organic soil amendments and use beneficial fungi and bacteria for control.',
      imagePath: 'assets/lance_nematode.jpg',
    ),
        Pest(  
      id: '7',
      name: 'Sting Nematode',
      scientificName: 'Belonolaimus spp.',
      category: '7',
      description: 'Highly damaging nematodes that attack roots, causing stunting, yellowing, and poor crop development.',
      prevention: 'Maintain proper irrigation, use soil amendments, and rotate crops.',
      treatment: 'Apply soil fumigants, use organic compost, and introduce predatory nematodes.',
      imagePath: 'assets/sting_nematode.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Lesion Nematode',
      scientificName: 'Pratylenchus spp.',
      category: '7',
      description: 'Migratory nematodes that feed on root tissue, leading to dark root lesions and secondary infections.',
      prevention: 'Use resistant plant varieties, rotate crops, and maintain soil health.',
      treatment: 'Apply biocontrol agents like mycorrhizal fungi and use nematicides when necessary.',
      imagePath: 'assets/lesion_nematode.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Dagger Nematode',
      scientificName: 'Xiphinema spp.',
      category: '7',
      description: 'Long nematodes that damage plant roots and transmit plant viruses, leading to severe crop losses.',
      prevention: 'Use certified disease-free planting material and maintain crop rotation.',
      treatment: 'Apply soil organic matter, use nematicides, and encourage beneficial soil microbes.',
      imagePath: 'assets/dagger_nematode.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Spiral Nematode',
      scientificName: 'Helicotylenchus spp.',
      category: '7',
      description: 'Nematodes that coil around roots and cause reduced nutrient uptake, leading to poor plant vigor.',
      prevention: 'Practice crop rotation, maintain soil fertility, and use resistant plant varieties.',
      treatment: 'Apply biological control methods such as nematode-trapping fungi and organic amendments.',
      imagePath: 'assets/spiral_nematode.jpg',
    ),
        Pest(  
      id: '7',
      name: 'Bulb and Stem Nematode',
      scientificName: 'Ditylenchus dipsaci',
      category: '7',
      description: 'Parasitic nematodes that invade stems, bulbs, and leaves, causing distorted growth and tissue decay.',
      prevention: 'Use nematode-free bulbs, avoid infested soil, and apply proper sanitation.',
      treatment: 'Use hot water treatment for bulbs, apply nematicides, and introduce beneficial nematodes.',
      imagePath: 'assets/bulb_and_stem_nematode.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Pine Wood Nematode',
      scientificName: 'Bursaphelenchus xylophilus',
      category: '7',
      description: 'A destructive nematode that causes pine wilt disease, leading to rapid tree decline and death.',
      prevention: 'Use resistant tree species, monitor for infected trees, and apply quarantine measures.',
      treatment: 'Remove and destroy infected trees, use insecticides to control beetle vectors, and apply biological control methods.',
      imagePath: 'assets/pinewood_nematode.jpg',
    ),
    Pest(  
      id: '7',
      name: 'Awl Nematode',
      scientificName: 'Dolichodorus spp.',
      category: '7',
      description: 'Large nematodes that feed on plant roots, reducing root development and water uptake.',
      prevention: 'Maintain healthy soil, improve drainage, and rotate crops.',
      treatment: 'Use organic soil amendments, apply nematicides, and introduce beneficial microbes.',
      imagePath: 'assets/awl_nematode.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Dandelion',
      scientificName: 'Taraxacum officinale',
      category: '8',
      description: 'A perennial weed with yellow flowers and deep taproots, commonly found in lawns and gardens.',
      prevention: 'Maintain a dense, healthy lawn to outcompete weeds and apply mulch in garden beds.',
      treatment: 'Hand-pull or use a weeding tool to remove the taproot, or apply selective broadleaf herbicides.',
      imagePath: 'assets/dandelion.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Crabgrass',
      scientificName: 'Digitaria spp.',
      category: '8',
      description: 'A fast-growing annual grass that spreads aggressively in lawns and gardens, competing with desired plants.',
      prevention: 'Apply pre-emergent herbicides in early spring and maintain a thick lawn to prevent germination.',
      treatment: 'Hand-pull young plants before they set seed or apply post-emergent herbicides.',
      imagePath: 'assets/crabgrass.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Bindweed',
      scientificName: 'Convolvulus arvensis',
      category: '8',
      description: 'A deep-rooted, vining perennial weed that twines around plants, restricting their growth.',
      prevention: 'Use landscape fabric or mulch to suppress growth and prevent seed germination.',
      treatment: 'Repeated cutting, pulling, or applying systemic herbicides to eliminate root reserves.',
      imagePath: 'assets/bindweed.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Pigweed',
      scientificName: 'Amaranthus spp.',
      category: '8',
      description: 'A broadleaf annual weed that produces thousands of seeds and competes aggressively for nutrients.',
      prevention: 'Use mulch to block sunlight and prevent seed germination, and practice crop rotation.',
      treatment: 'Hand-pull young plants or apply non-selective herbicides for severe infestations.',
      imagePath: 'assets/pigweed.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Nutsedge',
      scientificName: 'Cyperus spp.',
      category: '8',
      description: 'A fast-spreading perennial weed with grass-like leaves and underground tubers.',
      prevention: 'Improve drainage to prevent favorable growing conditions and maintain a thick lawn.',
      treatment: 'Apply selective herbicides targeting sedges or manually remove tubers to prevent regrowth.',
      imagePath: 'assets/nutsedge.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Chickweed',
      scientificName: 'Stellaria media',
      category: '8',
      description: 'A low-growing annual weed with small white flowers, often found in cool, moist conditions.',
      prevention: 'Maintain healthy soil and mulch garden beds to prevent seed germination.',
      treatment: 'Hand-pull or hoe seedlings before they spread, or use pre-emergent herbicides.',
      imagePath: 'assets/chickweed.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Foxtail',
      scientificName: 'Setaria spp.',
      category: '8',
      description: 'An annual grassy weed with seed heads resembling a fox’s tail, which can be harmful to pets and livestock.',
      prevention: 'Mow grass regularly and overseed bare spots to prevent foxtail establishment.',
      treatment: 'Hand-pull young plants or apply post-emergent herbicides targeting grassy weeds.',
      imagePath: 'assets/foxtail.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Canada Thistle',
      scientificName: 'Cirsium arvense',
      category: '8',
      description: 'A highly invasive perennial weed with spiny leaves and extensive underground root systems.',
      prevention: 'Encourage competition with desirable plants and maintain thick turfgrass cover.',
      treatment: 'Repeated mowing or application of systemic herbicides to kill roots.',
      imagePath: 'assets/canada_thistle.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Lambsquarters',
      scientificName: 'Chenopodium album',
      category: '8',
      description: 'A fast-growing annual weed that competes with crops for nutrients and space.',
      prevention: 'Use mulch to block sunlight and prevent seed germination.',
      treatment: 'Hand-pull or hoe young plants before they set seed, or apply broadleaf herbicides.',
      imagePath: 'assets/lambsquarters.jpg',
    ),
    Pest(  
      id: '8',
      name: 'Johnsongrass',
      scientificName: 'Sorghum halepense',
      category: '8',
      description: 'A fast-growing perennial grass weed that spreads through rhizomes and seeds.',
      prevention: 'Prevent seed production by mowing before flowering and use crop rotation.',
      treatment: 'Use systemic herbicides or till soil deeply to remove rhizomes.',
      imagePath: 'assets/johnsongrass.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Late Blight',
      scientificName: 'Phytophthora infestans',
      category: '9',
      description: 'A devastating fungal-like pathogen that affects potatoes and tomatoes, causing dark lesions on leaves and fruit rot.',
      prevention: 'Use resistant crop varieties, avoid overhead watering, and ensure proper plant spacing.',
      treatment: 'Apply fungicides such as copper-based sprays and remove infected plants promptly.',
      imagePath: 'assets/late_blight.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Bacterial Wilt',
      scientificName: 'Ralstonia solanacearum',
      category: '9',
      description: 'A soilborne bacterial disease that causes wilting in tomatoes, potatoes, and bananas by blocking water transport.',
      prevention: 'Use disease-free seeds, practice crop rotation, and avoid contaminated irrigation water.',
      treatment: 'Apply biological control agents like Bacillus subtilis and remove infected plants.',
      imagePath: 'assets/bacterial_wilt.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Rust Disease',
      scientificName: 'Puccinia spp.',
      category: '9',
      description: 'A fungal pathogen causing orange, yellow, or brown pustules on leaves, affecting cereal crops and ornamentals.',
      prevention: 'Grow resistant crop varieties and avoid excessive moisture on plant surfaces.',
      treatment: 'Use fungicides like chlorothalonil or copper sprays and remove infected leaves.',
      imagePath: 'assets/rust_disease.jpg',
    ),
    Pest(  
      id: '5',
      name: 'Black Sigatoka',
      scientificName: 'Mycosphaerella fijiensis',
      category: '9',
      description: 'A banana disease that causes dark streaks on leaves, reducing photosynthesis and yield.',
      prevention: 'Use resistant banana varieties and maintain good field sanitation.',
      treatment: 'Apply systemic fungicides and remove infected leaves.',
      imagePath: 'assets/black_sigatoka.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Damping-Off',
      scientificName: 'Pythium spp.',
      category: '9',
      description: 'A fungal-like pathogen affecting seedlings, causing rot and collapse before or after emergence.',
      prevention: 'Use sterile soil, avoid overwatering, and improve air circulation.',
      treatment: 'Apply biological fungicides and use fungicide-treated seeds.',
      imagePath: 'assets/damping_off.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Fire Blight',
      scientificName: 'Erwinia amylovora',
      category: '9',
      description: 'A bacterial disease that affects apples and pears, causing blackened, withered branches resembling fire damage.',
      prevention: 'Prune affected branches, disinfect tools, and plant resistant varieties.',
      treatment: 'Use copper-based sprays or biological controls like Bacillus subtilis.',
      imagePath: 'assets/fire_blight.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Smut Disease',
      scientificName: 'Ustilago spp.',
      category: '9',
      description: 'A fungal disease that causes black, spore-filled masses on cereal crops like corn and wheat.',
      prevention: 'Use disease-free seeds, rotate crops, and avoid excessive nitrogen application.',
      treatment: 'Apply seed treatments with fungicides and remove infected plants.',
      imagePath: 'assets/smut_disease.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Verticillium Wilt',
      scientificName: 'Verticillium spp.',
      category: '9',
      description: 'A fungal disease that infects the vascular system of plants, leading to wilting, yellowing, and stunted growth.',
      prevention: 'Plant resistant varieties, use proper crop rotation, and maintain healthy soil.',
      treatment: 'Remove and destroy infected plants, and apply biofungicides to suppress the fungus.',
      imagePath: 'assets/verticillium_wilt.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Fusarium Wilt',
      scientificName: 'Fusarium oxysporum',
      category: '9',
      description: 'A fungal disease that affects the vascular system, causing wilting, yellowing, and plant death.',
      prevention: 'Use disease-free seeds, avoid overwatering, and implement crop rotation.',
      treatment: 'Apply biological fungicides like Trichoderma spp. and remove infected plants.',
      imagePath: 'assets/fusarium_wilt.jpg',
    ),
    Pest(  
      id: '9',
      name: 'Sclerotinia Stem Rot',
      scientificName: 'Sclerotinia sclerotiorum',
      category: '9',
      description: 'A fungal disease that causes white mold growth on stems, leading to plant collapse.',
      prevention: 'Improve air circulation, space plants properly, and avoid excessive humidity.',
      treatment: 'Apply fungicides and remove infected plant debris from fields.',
      imagePath: 'assets/sclerotinia_stem_rot.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Black Widow Spider',
      scientificName: 'Latrodectus mactans',
      category: '10',
      description: 'A venomous spider known for its black body with a red hourglass marking on the abdomen. Its bite can cause severe pain and muscle cramps.',
      prevention: 'Seal cracks and crevices, reduce clutter, and remove webs from corners.',
      treatment: 'Use insecticides in infested areas, and seek medical attention if bitten.',
      imagePath: 'assets/black_widow_spider.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Brown Recluse Spider',
      scientificName: 'Loxosceles reclusa',
      category: '10',
      description: 'A venomous spider with a violin-shaped marking on its back, known for its necrotic bite.',
      prevention: 'Keep storage areas clean, wear gloves when handling old boxes, and seal entry points.',
      treatment: 'Use sticky traps, insecticides, and seek medical help if bitten.',
      imagePath: 'assets/brown_recluse_spider.jpeg',
    ),
    Pest(  
      id: '10',
      name: 'Wolf Spider',
      scientificName: 'Lycosidae',
      category: '10',
      description: 'A large, fast-moving spider that hunts prey rather than spinning webs. It is harmless to humans.',
      prevention: 'Reduce outdoor lighting to avoid attracting insects, and seal entry points.',
      treatment: 'Use residual insecticides or sticky traps to control populations.',
      imagePath: 'assets/wolf_spider.jpeg',
    ),
    Pest(  
      id: '10',
      name: 'Tarantula',
      scientificName: 'Theraphosidae',
      category: '10',
      description: 'Large, hairy spiders that are generally harmless to humans but can cause irritation with their urticating hairs.',
      prevention: 'Keep the home sealed and reduce outdoor clutter where they might hide.',
      treatment: 'Capture and release if found indoors, or use insecticides for control.',
      imagePath: 'assets/tarantula.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Scorpion',
      scientificName: 'Scorpiones',
      category: '10',
      description: 'Arachnids with a segmented tail ending in a venomous stinger, found in dry, warm environments.',
      prevention: 'Remove woodpiles and debris, seal cracks, and use door sweeps.',
      treatment: 'Apply residual insecticides around entry points, and seek medical help if stung.',
      imagePath: 'assets/scorpion.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Harvestman (Daddy Longlegs)',
      scientificName: 'Opiliones',
      category: '10',
      description: 'Non-venomous arachnids with long, thin legs. They do not produce silk or venom.',
      prevention: 'Reduce humidity, remove organic debris, and seal entry points.',
      treatment: 'No treatment necessary; they are harmless and beneficial in gardens.',
      imagePath: 'assets/harvestman.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Tick',
      scientificName: 'Ixodida',
      category: '10',
      description: 'Blood-feeding arachnids that transmit diseases like Lyme disease and Rocky Mountain spotted fever.',
      prevention: 'Wear protective clothing, use tick repellents, and keep grass trimmed.',
      treatment: 'Use acaricides in infested areas, and remove ticks using tweezers.',
      imagePath: 'assets/tick.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Mite',
      scientificName: 'Acari',
      category: '10',
      description: 'Tiny arachnids that infest plants, animals, and homes, causing irritation and disease transmission.',
      prevention: 'Maintain cleanliness, reduce humidity, and use essential oils as deterrents.',
      treatment: 'Use miticides or insecticidal soaps, and wash infested bedding or clothing.',
      imagePath: 'assets/mite.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Camel Spider',
      scientificName: 'Solifugae',
      category: '10',
      description: 'Fast-moving, non-venomous arachnids with strong jaws. They do not pose a danger to humans.',
      prevention: 'Seal cracks, reduce outdoor clutter, and remove hiding places.',
      treatment: 'Use sticky traps or insecticides to manage populations.',
      imagePath: 'assets/camel_spider.jpg',
    ),
    Pest(  
      id: '10',
      name: 'Redback Spider',
      scientificName: 'Latrodectus hasseltii',
      category: '10',
      description: 'A venomous spider similar to the Black Widow, commonly found in Australia.',
      prevention: 'Seal entry points, reduce outdoor debris, and use caution in infested areas.',
      treatment: 'Use insecticides and seek medical attention if bitten.',
      imagePath: 'assets/redback_spider.jpg',
    ),
  ];

  // Methods to interact with the data
  List<Category> getAllCategories() => List.unmodifiable(_categories);

  List<Pest> getAllPests() => List.unmodifiable(_pests);

  List<Pest> getPestsByCategory(String categoryId) => 
      _pests.where((pest) => pest.category == categoryId).toList();

  List<Pest> searchPests(String query) {
    if (query.isEmpty) return [];
    
    final queryLower = query.toLowerCase();
    return _pests.where((pest) {
      // Check name words
      final nameWords = pest.name.toLowerCase().split(' ');
      final hasNameMatch = nameWords.any((word) => 
          word.startsWith(queryLower) || pest.name.toLowerCase().contains(queryLower));
      
      // Check scientific name words
      final sciNameWords = pest.scientificName.toLowerCase().split(' ');
      final hasSciNameMatch = sciNameWords.any((word) => 
          word.startsWith(queryLower) || pest.scientificName.toLowerCase().contains(queryLower));
      
      // Check description
      final hasDescriptionMatch = pest.description.toLowerCase().contains(queryLower);
      
      return hasNameMatch || hasSciNameMatch || hasDescriptionMatch;
    }).toList();
  }

  Pest? getPestById(String id) {
    try {
      return _pests.firstWhere((pest) => pest.id == id);
    } catch (e) {
      return null;
    }
  }

  // Helper method to get category name by ID
  String getCategoryName(String categoryId) {
    return _categories.firstWhere(
      (category) => category.id == categoryId,
      orElse: () => Category(id: '', name: 'Unknown', description: '', iconPath: ''),
    ).name;
  }
}